### ISSUE TITLE
Python 3.X support!

### ISSUE THREAD

**Issue by pahaz** [mhaller/pyffmpeg#5]
```
Collecting pyffmpeg from git+git://github.com/mhaller/pyffmpeg.git#egg=pyffmpeg (from -r requirements.txt (line 1))
  Cloning git://github.com/mhaller/pyffmpeg.git to /private/var/folders/t3/z9_f5hg928q3gy1q0xhj7ttw0000gn/T/pip-build-3uvzvduo/pyffmpeg
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/t3/z9_f5hg928q3gy1q0xhj7ttw0000gn/T/pip-build-3uvzvduo/pyffmpeg/setup.py", line 9
        print "Remember: Edit at first ffmpegpath within setup.py"
                                                                 ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/t3/z9_f5hg928q3gy1q0xhj7ttw0000gn/T/pip-build-3uvzvduo/pyffmpeg

```

**Comment by iBobik** [comment]
This project seems more active: https://github.com/kkroening/ffmpeg-python
